/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        Map<Character,Integer> freq = new HashMap<>();
        for(char ch: s.toCharArray()){
            freq.put(ch,freq.getOrDefault(ch,0)+1);
        }
        for(char ch:t.toCharArray()){
            if(!freq.containsKey(ch)){
                return ch;
            }
            else{
                int val = freq.get(ch);
                freq.put(ch,val-1);
            }
        }
        for(Map.Entry<Character,Integer> e: freq.entrySet()){
            if(e.getValue()!=0)
                return e.getKey();
        }
        return '\0';
    }
}
